#!/usr/bin/env bash

print_help() {
	echo "spoon - ssh into ec2 instances easily"
	echo "usage: spoon <identifier>"
}

has_short_flag() {
	flag="$1"
	shift
	args="$@"
	for arg in $args; do
		if [ "${arg:0:1}" = - ] && [ "${arg:1:1}" != - ] && [[ "$arg" =~ "$flag" ]]; then
			return 0
		fi
	done
	return 1
}

has_long_flag() {
	flag="$1"
	shift
	args="$@"
	for arg in $args; do
		if [ "${arg:0:2}" = -- ] && [[ "$arg" == --"$flag" ]]; then
			return 0
		fi
	done
	return 1
}

################################################
################################################
################################################

query_aws() {
	aws ec2 describe-instances --query 'Reservations[*].Instances[*].{id: InstanceId, ip: PublicIpAddress, state: State.Name, service: (Tags[?Key == `"Name"`].Value)[0]}[0]' "${@}"
}

query_aws_by_name() {
	query_aws --filters "Name=tag:Name,Values=*$1*"
}

query_aws_by_id() {
	query_aws --instance-ids "$1"
}

################################################
################################################
################################################

ssh_multiple() {
	if [[ "$TERM_PROGRAM" == "iTerm.app" ]]; then
	    i2cssh --login root $1
	    echo hint: press Cmd+Shift+I to send your keyboard input to all the instances
	else
	    csshx --login root $1
	fi
}

################################################
################################################
################################################

if [[ $# -lt 1 ]]; then
	print_help
	exit 1
fi

if has_short_flag h "$@" || has_long_flag 'help' "$@"; then
	print_help
	exit 0
fi

if has_short_flag i "$@" || has_long_flag 'instance-id' "$@"; then
	use_instance_id=1
else
	use_instance_id=0
fi

if has_short_flag p "$@" || has_long_flag 'preprod' "$@"; then
	only_preprod=1
else
	only_preprod=0
fi

if has_short_flag P "$@" || has_long_flag 'prod' "$@"; then
	only_prod=1
else
	only_prod=0
fi

specifier="${*: -1}"
if [[ $use_instance_id = 1 ]]; then
	nodes=$(query_aws_by_id $specifier)
else
	nodes=$(query_aws_by_name $specifier)
fi

if [[ $only_preprod = 1 ]]; then
	nodes=$(echo ${nodes} | jq 'map(select(.service | test("preprod|-pp")))')
elif [[ $only_prod = 1 ]]; then
	nodes=$(echo ${nodes} | jq 'map(select(.service | test("preprod|-pp") | not))')
fi

node_count=$(echo "${nodes}" | jq '. | length')
if [[ "${node_count}" -eq 0 ]]; then
	echo No node found for this identifier.
	exit 1
elif [[ "${node_count}" -gt 1 ]]; then
	ips=$(echo "${nodes}" | jq '.[].ip' | tr -d '"' | xargs)
	ssh_multiple "${ips}"
else
	ip=$(echo "${nodes}" | jq '.[0].ip' | tr -d '"')
	ssh -o StrictHostKeyChecking=no -l root  "${ip}"
fi
