#!/usr/bin/env bash

SPOON_VERSION=2.3.1

# https://stackoverflow.com/a/246128
SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
  DIR="$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
DIR="$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )"

lib_root="${DIR}/lib"
source "${lib_root}/0-utils.bash"
source "${lib_root}/1-usage.bash"
source "${lib_root}/2-query.bash"
source "${lib_root}/3-filter.bash"
source "${lib_root}/4-select.bash"
source "${lib_root}/5-ssh.bash"

spoon_args=( "${@}" )
spoon_about
spoon_set_args
spoon_check_args
spoon_verybose_print_args

spoon_get_instances
spoon_filter_for_environment
spoon_filter_for_first
spoon_select_from_multiple

spoon_ssh
