version: 2
jobs:
  build:
    docker:
      - image: endreymarca/bats-ext
    steps:
      - checkout
      - run:
        name: Lint with shellcheck
        command: shellcheck spoon
      - run:
        name: Run bats test suite
        command: bats test/*.bats
